services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks:
      - ml-scorer
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    networks:
      - ml-scorer
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    networks:
      - ml-scorer
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"

  kafka-setup:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - ml-scorer
    entrypoint: [ "/bin/bash", "-c" ]
    command: |
      "
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic transactions --partitions 3
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic scoring --partitions 3
      "

  fraud_detector:
    build: ./fraud_detector
    networks:
      - ml-scorer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - kafka

  result_saver:
    build: ./result_saver
    networks:
      - ml-scorer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      DATABASE_URL: "postgresql://user:password@db:5432/fraud_db"
    depends_on:
      - kafka
      - db

  interface:
    build: ./interface
    networks:
      - ml-scorer
    ports:
      - "8501:8501"
    environment:
      KAFKA_BROKERS: "kafka:9092"
      DATABASE_URL: "postgresql://user:password@db:5432/fraud_db"
    depends_on:
      - kafka
      - db

networks:
  ml-scorer:
    driver: bridge